/**
 * Dynamo Python Script Generator
 * Generates ready-to-use Python scripts for Revit/Dynamo
 */

export function generateDynamoScript(jsonFilePath: string): string {
  // Convert Windows path to proper format if needed
  const formattedPath = jsonFilePath.replace(/\\/g, '\\\\');

  return `"""
COMPLETE BUILDING CREATOR - Paste this into a Dynamo Python node

Creates ALL elements from floor plan JSON: Walls, Doors, Windows, and Rooms
Generated by OCR Testing Tool - Floor Plan to Revit Conversion

Required: ONLY the JSON file path (IN[0])
Auto-selects: First available families and level

SINGLE-NODE WORKFLOW:
  [File Path] → [Python Script with this code] → Complete Building!

Processing Order:
  1. Walls (structural support)
  2. Doors (require walls)
  3. Windows (require walls)
  4. Rooms (require walls to define boundaries)
"""

import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')
from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Architecture import Room
from Autodesk.Revit.DB.Structure import StructuralType
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

import json

# Get current Revit document
doc = DocumentManager.Instance.CurrentDBDocument

# INPUT - JSON file path from Dynamo input node
# Or use the hardcoded path below for quick testing
json_file_path = IN[0] if IN[0] else "${formattedPath}"

# OUTPUT variables
created_walls = []
created_doors = []
created_windows = []
created_rooms = []
error_log = []
stats = {
    'walls': {'success': 0, 'failed': 0},
    'doors': {'success': 0, 'failed': 0},
    'windows': {'success': 0, 'failed': 0},
    'rooms': {'success': 0, 'failed': 0}
}

# Conversion factor
MM_TO_FEET = 1.0 / 304.8

# ============================================================
# HELPER FUNCTIONS
# ============================================================

def find_nearest_wall(walls, target_point):
    """Find the nearest wall to a target point."""
    if not walls:
        return None

    nearest_wall = None
    min_distance = float('inf')

    for wall in walls:
        try:
            location_curve = wall.Location
            if location_curve and hasattr(location_curve, 'Curve'):
                curve = location_curve.Curve
                result = curve.Project(target_point)
                if result:
                    distance = result.Distance
                    if distance < min_distance:
                        min_distance = distance
                        nearest_wall = wall
        except:
            continue

    return nearest_wall


def create_wall_from_coords(start_mm, end_mm, level, wall_type, height_mm):
    """Create a wall from millimeter coordinates."""
    try:
        # Convert mm to feet
        start_ft = XYZ(
            start_mm['x'] * MM_TO_FEET,
            start_mm['y'] * MM_TO_FEET,
            0
        )
        end_ft = XYZ(
            end_mm['x'] * MM_TO_FEET,
            end_mm['y'] * MM_TO_FEET,
            0
        )

        # Create line
        line = Line.CreateBound(start_ft, end_ft)

        # Create wall
        height_ft = height_mm * MM_TO_FEET
        wall = Wall.Create(doc, line, level.Id, False)
        wall.get_Parameter(BuiltInParameter.WALL_USER_HEIGHT_PARAM).Set(height_ft)

        return wall
    except Exception as e:
        error_log.append(f"Wall creation error: {str(e)}")
        return None


def create_door_instance(coords_mm, level, door_family, walls):
    """Create a door instance at specified coordinates."""
    try:
        # Convert mm to feet
        point_ft = XYZ(
            coords_mm[0]['x'] * MM_TO_FEET,
            coords_mm[0]['y'] * MM_TO_FEET,
            0
        )

        # Find nearest wall
        host_wall = find_nearest_wall(walls, point_ft)
        if not host_wall:
            error_log.append("Door: No host wall found")
            return None

        # Get wall curve and project point
        location_curve = host_wall.Location
        curve = location_curve.Curve
        result = curve.Project(point_ft)
        insertion_point = result.XYZPoint

        # Create door instance
        door = doc.Create.NewFamilyInstance(
            insertion_point,
            door_family,
            host_wall,
            level,
            StructuralType.NonStructural
        )

        return door
    except Exception as e:
        error_log.append(f"Door creation error: {str(e)}")
        return None


def create_window_instance(coords_mm, level, window_family, walls):
    """Create a window instance at specified coordinates."""
    try:
        # Convert mm to feet
        point_ft = XYZ(
            coords_mm[0]['x'] * MM_TO_FEET,
            coords_mm[0]['y'] * MM_TO_FEET,
            0
        )

        # Find nearest wall
        host_wall = find_nearest_wall(walls, point_ft)
        if not host_wall:
            error_log.append("Window: No host wall found")
            return None

        # Get wall curve and project point
        location_curve = host_wall.Location
        curve = location_curve.Curve
        result = curve.Project(point_ft)
        insertion_point = result.XYZPoint

        # Create window instance with sill height
        window = doc.Create.NewFamilyInstance(
            insertion_point,
            window_family,
            host_wall,
            level,
            StructuralType.NonStructural
        )

        # Set sill height (900mm = ~3 feet)
        sill_param = window.get_Parameter(BuiltInParameter.INSTANCE_SILL_HEIGHT_PARAM)
        if sill_param:
            sill_param.Set(900 * MM_TO_FEET)

        return window
    except Exception as e:
        error_log.append(f"Window creation error: {str(e)}")
        return None


def create_room_from_polygon(coords_mm, level, room_name):
    """Create a room at the center of a polygon."""
    try:
        # Calculate center point
        avg_x = sum(c['x'] for c in coords_mm) / len(coords_mm)
        avg_y = sum(c['y'] for c in coords_mm) / len(coords_mm)

        # Convert to feet
        center_ft = XYZ(
            avg_x * MM_TO_FEET,
            avg_y * MM_TO_FEET,
            0
        )

        # Create room
        room = doc.Create.NewRoom(level, UV(center_ft.X, center_ft.Y))

        # Set room name
        if room_name:
            room.Name = room_name

        return room
    except Exception as e:
        error_log.append(f"Room creation error: {str(e)}")
        return None


# ============================================================
# MAIN PROCESSING
# ============================================================

# Load JSON file
try:
    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
except Exception as e:
    OUT = [[], [], [], [], {'error': f"Failed to load JSON: {str(e)}"}, error_log]
    raise

# Auto-select first available types
wall_types = FilteredElementCollector(doc).OfClass(WallType).ToElements()
wall_type = wall_types[0] if wall_types else None

door_symbols = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Doors).OfClass(FamilySymbol).ToElements()
door_family = next((s for s in door_symbols if s.IsActive), door_symbols[0] if door_symbols else None)

window_symbols = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Windows).OfClass(FamilySymbol).ToElements()
window_family = next((s for s in window_symbols if s.IsActive), window_symbols[0] if window_symbols else None)

levels = FilteredElementCollector(doc).OfClass(Level).ToElements()
level = levels[0] if levels else None

if not level:
    error_log.append("No level found in project")
    OUT = [[], [], [], [], stats, error_log]
    raise Exception("No level found")

# Activate symbols if needed
if door_family and not door_family.IsActive:
    door_family.Activate()
if window_family and not window_family.IsActive:
    window_family.Activate()

# Separate elements by type
walls_data = [e for e in data['elements'] if e['type'] == 'wall']
doors_data = [e for e in data['elements'] if e['type'] == 'door']
windows_data = [e for e in data['elements'] if e['type'] == 'window']
rooms_data = [e for e in data['elements'] if e['type'] == 'room']

# Start transaction
TransactionManager.Instance.EnsureInTransaction(doc)

try:
    # 1. Create walls first
    error_log.append(f"Creating {len(walls_data)} walls...")
    for wall_data in walls_data:
        coords = wall_data['geometry']['coordinates_mm']
        if len(coords) >= 2:
            height = wall_data['properties'].get('height', 3000)
            wall = create_wall_from_coords(coords[0], coords[1], level, wall_type, height)
            if wall:
                created_walls.append(wall)
                stats['walls']['success'] += 1
            else:
                stats['walls']['failed'] += 1

    # 2. Create doors
    if door_family:
        error_log.append(f"Creating {len(doors_data)} doors...")
        for door_data in doors_data:
            coords = door_data['geometry']['coordinates_mm']
            door = create_door_instance(coords, level, door_family, created_walls)
            if door:
                created_doors.append(door)
                stats['doors']['success'] += 1
            else:
                stats['doors']['failed'] += 1

    # 3. Create windows
    if window_family:
        error_log.append(f"Creating {len(windows_data)} windows...")
        for window_data in windows_data:
            coords = window_data['geometry']['coordinates_mm']
            window = create_window_instance(coords, level, window_family, created_walls)
            if window:
                created_windows.append(window)
                stats['windows']['success'] += 1
            else:
                stats['windows']['failed'] += 1

    # 4. Create rooms
    error_log.append(f"Creating {len(rooms_data)} rooms...")
    for room_data in rooms_data:
        coords = room_data['geometry']['coordinates_mm']
        room_name = room_data['properties'].get('name', '')
        room = create_room_from_polygon(coords, level, room_name)
        if room:
            created_rooms.append(room)
            stats['rooms']['success'] += 1
        else:
            stats['rooms']['failed'] += 1

    error_log.append(f"Completed! Created {len(created_walls)} walls, {len(created_doors)} doors, {len(created_windows)} windows, {len(created_rooms)} rooms")

except Exception as e:
    error_log.append(f"Processing error: {str(e)}")
finally:
    TransactionManager.Instance.TransactionTaskDone()

# OUTPUT
OUT = [created_walls, created_doors, created_windows, created_rooms, stats, error_log]
`;
}

/**
 * Generate usage instructions for the Dynamo script
 */
export function generateDynamoInstructions(): string {
  return `# How to Use the Dynamo Script in Revit

## Quick Start (3 Steps)

### Step 1: Open Dynamo in Revit
1. Open your Revit project
2. Go to: **Manage** tab → **Visual Programming** → **Dynamo**
3. In Dynamo, create a new workspace

### Step 2: Create Python Script Node
1. In Dynamo, search for "**Python Script**" in the library
2. Drag it onto the canvas
3. Double-click the Python Script node to open the editor
4. **Copy-paste the entire generated script** into the editor
5. Click "Run" or close the editor

### Step 3: (Optional) Add File Path Input
**Option A: Use hardcoded path (Easiest)**
- The script already has the JSON path hardcoded
- Just run it directly!

**Option B: Use Dynamo input node**
1. Add a "**File Path**" node
2. Connect it to the Python Script node's input
3. Select your JSON file

## What the Script Creates

The script automatically creates:
- ✅ **Walls** - All wall segments with correct dimensions
- ✅ **Doors** - Automatically placed on nearest walls
- ✅ **Windows** - Wall-hosted with sill heights
- ✅ **Rooms** - Created at polygon centers with labels

## Output

The Python node outputs 6 values:
1. **List of Walls** - Created wall elements
2. **List of Doors** - Created door instances
3. **List of Windows** - Created window instances
4. **List of Rooms** - Created room elements
5. **Statistics** - Success/failure counts
6. **Error Log** - Any issues encountered

## Troubleshooting

**"No level found"**
→ Make sure your Revit project has at least one level

**"No host wall found" for doors/windows**
→ Walls are created first, then doors/windows attach to them

**"Failed to load JSON"**
→ Check that the file path is correct (use \\\\ or / for separators)

**Elements not appearing**
→ Check the error log output from the Python node

## Tips

- The script uses the **first available** wall type, door family, and window family
- Default heights: Walls = 3000mm, Doors = 2100mm, Windows = 1200mm
- Coordinates are automatically converted from millimeters to feet (Revit's unit)
- Rooms are placed at the center of detected polygons
`;
}
