import type { AccuracyMetrics } from './accuracy';

/**
 * HTML Report Generator for OCR Testing
 * Creates self-contained HTML reports with embedded CSS
 */

export function generateHTMLReport(
  results: any[],
  groundTruth?: string
): string {
  const timestamp = new Date().toLocaleString();

  // Calculate total cost
  const totalCost = results.reduce((sum, r) => sum + (r.cost || 0), 0);
  const totalTime = results.reduce(
    (sum, r) => sum + (r.processingTime || 0),
    0
  );

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OCR Test Results - ${timestamp}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f5f5f5;
      padding: 20px;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      padding: 40px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    header {
      border-bottom: 3px solid #4f46e5;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }

    h1 {
      color: #4f46e5;
      font-size: 2em;
      margin-bottom: 10px;
    }

    .metadata {
      color: #666;
      font-size: 0.9em;
    }

    h2 {
      color: #333;
      margin-top: 40px;
      margin-bottom: 20px;
      font-size: 1.5em;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 10px;
    }

    h3 {
      color: #4f46e5;
      margin-top: 30px;
      margin-bottom: 15px;
      font-size: 1.2em;
    }

    h4 {
      color: #666;
      margin-top: 20px;
      margin-bottom: 10px;
      font-size: 1em;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
      background: white;
    }

    th, td {
      padding: 12px;
      text-align: left;
      border: 1px solid #e5e7eb;
    }

    th {
      background: #f9fafb;
      font-weight: 600;
      color: #374151;
    }

    tr:hover {
      background: #f9fafb;
    }

    .metric-value {
      font-weight: 600;
      color: #4f46e5;
    }

    .success {
      color: #10b981;
    }

    .error {
      color: #ef4444;
    }

    .warning {
      color: #f59e0b;
    }

    .badge {
      display: inline-block;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 0.85em;
      font-weight: 500;
    }

    .badge-success {
      background: #d1fae5;
      color: #065f46;
    }

    .badge-error {
      background: #fee2e2;
      color: #991b1b;
    }

    .comparison {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      margin: 20px 0;
    }

    .comparison-box {
      background: #f9fafb;
      padding: 15px;
      border-radius: 4px;
      border-left: 4px solid #4f46e5;
    }

    .comparison-box h4 {
      margin-top: 0;
    }

    pre {
      white-space: pre-wrap;
      word-wrap: break-word;
      background: #f9fafb;
      padding: 15px;
      border-radius: 4px;
      border: 1px solid #e5e7eb;
      font-size: 0.9em;
      line-height: 1.5;
    }

    .metric-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 15px;
      margin: 20px 0;
    }

    .metric-card {
      background: #f9fafb;
      padding: 15px;
      border-radius: 4px;
      border-left: 4px solid #4f46e5;
    }

    .metric-card-title {
      font-size: 0.85em;
      color: #6b7280;
      margin-bottom: 5px;
    }

    .metric-card-value {
      font-size: 1.5em;
      font-weight: 600;
      color: #4f46e5;
    }

    .char-analysis {
      background: #fef3c7;
      border-left: 4px solid #f59e0b;
      padding: 15px;
      margin: 15px 0;
      border-radius: 4px;
    }

    footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #6b7280;
      font-size: 0.9em;
    }

    @media print {
      body {
        background: white;
        padding: 0;
      }

      .container {
        box-shadow: none;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>OCR Test Results</h1>
      <p class="metadata">Generated: ${timestamp}</p>
      <p class="metadata">Total Cost: ¥${totalCost.toFixed(2)} | Total Time: ${formatTime(totalTime)}</p>
    </header>

    ${generateSummarySection(results)}

    ${results
      .map((result, index) => generateProcessorSection(result, index + 1, groundTruth))
      .join('\n')}

    <footer>
      <p>Generated by OCR Testing Tool v1.0</p>
    </footer>
  </div>
</body>
</html>
  `.trim();
}

function generateSummarySection(results: any[]): string {
  return `
    <section>
      <h2>Summary</h2>
      <table>
        <thead>
          <tr>
            <th>Processor</th>
            <th>Status</th>
            <th>Order-Dep CER</th>
            <th>Order-Indep CER</th>
            <th>Cost</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
          ${results
            .map(
              (r) => `
            <tr>
              <td><strong>${r.processorId || r.tool}</strong></td>
              <td>
                ${
                  r.success
                    ? '<span class="badge badge-success">Success</span>'
                    : `<span class="badge badge-error">Failed</span>`
                }
              </td>
              <td class="metric-value">${r.accuracy ? (r.accuracy.cer * 100).toFixed(2) + '%' : 'N/A'}</td>
              <td class="metric-value">${r.accuracy ? (r.accuracy.orderIndependentCer * 100).toFixed(2) + '%' : 'N/A'}</td>
              <td>¥${(r.cost || 0).toFixed(2)}</td>
              <td>${formatTime(r.processingTime || 0)}</td>
            </tr>
          `
            )
            .join('')}
        </tbody>
      </table>
    </section>
  `;
}

function generateProcessorSection(
  result: any,
  index: number,
  groundTruth?: string
): string {
  const accuracy: AccuracyMetrics | undefined = result.accuracy;

  return `
    <section>
      <h2>${index}. ${result.processorId || result.tool}</h2>

      ${
        result.error
          ? `<div class="badge badge-error">Error: ${result.error}</div>`
          : ''
      }

      ${
        accuracy
          ? `
      <div class="metric-grid">
        <div class="metric-card">
          <div class="metric-card-title">Order-Dependent CER</div>
          <div class="metric-card-value">${(accuracy.cer * 100).toFixed(2)}%</div>
        </div>
        <div class="metric-card">
          <div class="metric-card-title">Order-Independent CER</div>
          <div class="metric-card-value">${(accuracy.orderIndependentCer * 100).toFixed(2)}%</div>
        </div>
        <div class="metric-card">
          <div class="metric-card-title">Precision</div>
          <div class="metric-card-value">${(accuracy.precision * 100).toFixed(2)}%</div>
        </div>
        <div class="metric-card">
          <div class="metric-card-title">Recall</div>
          <div class="metric-card-value">${(accuracy.recall * 100).toFixed(2)}%</div>
        </div>
        <div class="metric-card">
          <div class="metric-card-title">F1 Score</div>
          <div class="metric-card-value">${(accuracy.f1Score * 100).toFixed(2)}%</div>
        </div>
        <div class="metric-card">
          <div class="metric-card-title">Edit Distance</div>
          <div class="metric-card-value">${accuracy.editDistance}</div>
        </div>
      </div>

      ${generateCharacterAnalysis(accuracy)}

      <h3>Text Comparison</h3>
      <div class="comparison">
        <div class="comparison-box">
          <h4>OCR Output (${result.rawText?.length || 0} chars)</h4>
          <pre>${escapeHtml(result.rawText || '(empty)')}</pre>
        </div>
        <div class="comparison-box">
          <h4>Ground Truth</h4>
          <pre>${escapeHtml(groundTruth || '(not provided)')}</pre>
        </div>
      </div>
      `
          : '<p>No accuracy metrics available (ground truth not provided)</p>'
      }

      <h3>Metadata</h3>
      <table>
        <tbody>
          <tr><td><strong>Processing Time</strong></td><td>${formatTime(result.processingTime || 0)}</td></tr>
          <tr><td><strong>Cost</strong></td><td>¥${(result.cost || 0).toFixed(2)}</td></tr>
          <tr><td><strong>Confidence</strong></td><td>${((result.confidence || 0) * 100).toFixed(1)}%</td></tr>
          <tr><td><strong>Text Length</strong></td><td>${result.rawText?.length || 0} characters</td></tr>
          ${result.metadata?.wordCount ? `<tr><td><strong>Word Count</strong></td><td>${result.metadata.wordCount}</td></tr>` : ''}
          ${result.metadata?.pageCount ? `<tr><td><strong>Page Count</strong></td><td>${result.metadata.pageCount}</td></tr>` : ''}
        </tbody>
      </table>
    </section>
  `;
}

function generateCharacterAnalysis(accuracy: AccuracyMetrics): string {
  const hasMissing = Object.keys(accuracy.missingChars).length > 0;
  const hasExtra = Object.keys(accuracy.extraChars).length > 0;

  if (!hasMissing && !hasExtra) {
    return '';
  }

  return `
    <div class="char-analysis">
      <h4>Order-Independent Character Analysis</h4>
      ${
        hasMissing
          ? `<p><strong>Missing Characters:</strong> ${Object.entries(accuracy.missingChars)
              .map(([char, count]) => `"${char}" (${count}x)`)
              .join(', ')}</p>`
          : ''
      }
      ${
        hasExtra
          ? `<p><strong>Extra Characters:</strong> ${Object.entries(accuracy.extraChars)
              .map(([char, count]) => `"${char}" (${count}x)`)
              .join(', ')}</p>`
          : ''
      }
    </div>
  `;
}

function formatTime(ms: number): string {
  if (ms < 1000) return `${Math.round(ms)}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(2)}s`;
  const minutes = Math.floor(ms / 60000);
  const seconds = ((ms % 60000) / 1000).toFixed(0);
  return `${minutes}m ${seconds}s`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
